    - name: Create Pod YAML and save to /opt/tmp
      run: |
        cat <<EOF | sudo tee /opt/tmp/vault-test-pod.yaml > /dev/null
        apiVersion: v1
        kind: Pod
        metadata:
          name: vault-test-pod
          namespace: default
        spec:
          containers:
          - name: app
            image: busybox
            command: ["sh", "-c", "echo My secret is \$SECRET_ENV; sleep 3600"]
            env:
            - name: SECRET_ENV
              value: "${SECRET_VALUE}"
        EOF

    - name: Confirm YAML file exists
      run: |
        ls -l /opt/tmp/vault-test-pod.yaml
        cat /opt/tmp/vault-test-pod.yaml

    - name: Deploy Pod using kubectl
      run: |
        kubectl apply -f /opt/tmp/vault-test-pod.yaml
