name: Vault Secret to Mounted File in Pod

on:
  workflow_dispatch:

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ vars.API_URL }}
      VERIFY_CA: ${{ vars.VERIFY_CA }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CERTIFICATE: ${{ secrets.CERTIFICATE }}
      CERTIFICATE_KEY: ${{ secrets.CERTIFICATE_KEY }}
    steps:
      - name: Checkout repo (required to access GitHub context)
        uses: actions/checkout@v3

      - name: Retrieve secret using BeyondTrust Secrets Safe Action
        id: secretsafe
        uses: BeyondTrust/secrets-safe-action@v1
        with:
          SECRET_PATH: '{"path": "nav/docker", "output_id": "docker"}'

      - name: Extract secret value and create Kubernetes secret file
        run: |
          mkdir -p /opt/tmp
          secret_response="${{ steps.secretsafe.outputs.secret }}"
          echo "$secret_response" | jq -r '.value' > /opt/tmp/secret.txt

      - name: Upload secret file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: secret-file
          path: /opt/tmp/secret.txt

  deploy-pod:
    runs-on: self-hosted
    needs: retrieve-secret
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download secret artifact
        uses: actions/download-artifact@v3
        with:
          name: secret-file
          path: /opt/tmp

      - name: Debug Secret Content
        run: cat /opt/tmp/secret.txt

      - name: Create Kubernetes secret from retrieved file
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl delete secret vault-secret --ignore-not-found
          kubectl create secret generic vault-secret --from-file=secret.txt=/opt/tmp/secret.txt

      - name: Create Pod YAML
        run: |
          mkdir -p /opt/tmp
          cat <<EOF > /opt/tmp/vault-test-pod.yaml
          apiVersion: v1
          kind: Pod
          metadata:
            name: jumpoint-pod
            namespace: default
          spec:
            containers:
            - name: jumpoint-name
              image: beyondtrust/sra-jumpoint:1cd9128ba1
              env:
              - name: DEPLOY_KEY
                valueFrom:
                  secretKeyRef:
                    name: vault-secret
                    key: secret.txt
              volumeMounts:
              - name: jpt-vol
                mountPath: /jpt
              securityContext:
                capabilities:
                  add: ["IPC_LOCK"]
            volumes:
            - name: jpt-vol
              hostPath:
                path: /data
                type: Directory
          EOF

      - name: Deploy Pod
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f /opt/tmp/vault-test-pod.yaml
